theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 干猫粮

# 对你自己的简洁描述
description: 可爱又迷人的小猫咪

# 你的美照地址
logo: /123ll4321/Resume/blob/master/微信图片_20201108081805.jpg

# 你的名字
name: 星期五

# 你的联系方式
phone: 188888888888

# 你的邮箱
email: 3522554@qq.com

# 你目前的住址
address: 湖南

# 你毕业院校
school: 圣文森特·圣玛丽高中

# 你的专业
profession: 专业干饭猫

# 你的学位
degree: 高中没毕业

# 你获得过的证书或奖励
credential: 三届MVP/三届NBA冠军
